apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-marketplace.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: standard
